pipeline {
    agent any 
    
    // USUNIĘTO BLOK 'tools'

    parameters {
        // POZOSTAŁ TYLKO PARAMETR AKCJI
        choice(
            name: 'ACTION',
            choices: ['build', 'destroy'],
            description: 'Wybierz akcję: build (init, plan, apply) lub destroy.'
        )
    }

    stages {
        
        stage('Initialize & Validate') {
            steps { 
                // USUNIĘTO LINIE: env.AWS_DEFAULT_REGION = params.AWS_REGION
                
                echo "Uruchamiam inicjalizację i walidację."
                
                dir('infrastructure') {
                    sh 'terraform init' 
                    sh 'terraform validate'
                }
            } 
        }
        
        stage('Terraform Build (Plan & Apply)') {
            when {
                expression { return params.ACTION == 'build' }
            }
            steps {
                echo "Akcja BUILD wybrana."
                dir('infrastructure') {
                    sh 'terraform plan -out=tfplan' 
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }

        stage('Terraform Destroy') {
            when {
                expression { return params.ACTION == 'destroy' }
            }
            steps {
                echo "Akcja DESTROY wybrana. UWAGA: Infrastruktura zostanie usunięta."
                dir('infrastructure') {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}