apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: apache
        image: selansis/k8s_challenge:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: feature-toggle-config
            key: FEATURE_DARK_MODE
        env: 
        - name: DB_HOST
          value: localhost
        - name: DB_USER
          value: ecomuser
        - name: DB_PASSWORD
          value: ecompassword
        - name: DB_NAME
          value: ecomdb