
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: apache
          image: selansis/k8s_challenge:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
                httpGet:
                  path: /index.php
                  port: 80
                initialDelaySeconds: 15
                periodSeconds: 5
          livenessProbe:
                httpGet:
                  path: /index.php
                  port: 80
                initialDelaySeconds: 15
                periodSeconds: 5    
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_USER
              value: "ecomuser"
            - name: DB_PASSWORD
              value: "ecompassword"
            - name: DB_NAME
              value: "ecomdb"
            - name: FEATURE_DARK_MODE
              valueFrom:
                configMapKeyRef:
                  name: feature-toggle-config
                  key: FEATURE_DARK_MODE
          resources:
            requests:
              memory: "2Gi"
              cpu: 1